
project_id = "pnbkvdjmngbpqhcnykuk"

[functions.scrape-recipe]
verify_jwt = true
[functions.scrape-recipe-enhanced]
verify_jwt = true
[functions.extract-youtube-recipe]
verify_jwt = true
[functions.scrape-sales]
verify_jwt = true
[functions.adapt-recipe-for-restrictions]
verify_jwt = true
