import { supabase } from "@/integrations/supabase/client";
import type { UserProfile } from "./userProfiles";

export interface WorkoutShare {
  id: string;
  workout_id: string;
  shared_by_user_id: string;
  is_public: boolean;
  share_code: string;
  view_count: number;
  created_at: string;
}

export interface WorkoutLike {
  id: string;
  workout_id: string;
  user_id: string;
  created_at: string;
}

export interface WorkoutComment {
  id: string;
  workout_id: string;
  user_id: string;
  comment: string;
  created_at: string;
  user_profile?: UserProfile;
}

/**
 * Share a workout and generate a unique share code
 */
export const shareWorkout = async (
  workoutId: string,
  userId: string,
  isPublic: boolean = false
): Promise<WorkoutShare> => {
  try {
    // Check if workout is already shared
    const { data: existing } = await supabase
      .from("workout_shares")
      .select("*")
      .eq("workout_id", workoutId)
      .eq("shared_by_user_id", userId)
      .single();

    if (existing) {
      // Update existing share
      const { data, error } = await supabase
        .from("workout_shares")
        .update({ is_public: isPublic })
        .eq("id", existing.id)
        .select()
        .single();

      if (error) throw error;
      return data as WorkoutShare;
    }

    // Create new share (share_code is auto-generated by trigger)
    const { data, error } = await supabase
      .from("workout_shares")
      .insert({
        workout_id: workoutId,
        shared_by_user_id: userId,
        is_public: isPublic,
      })
      .select()
      .single();

    if (error) throw error;
    return data as WorkoutShare;
  } catch (error) {
    console.error("Error sharing workout:", error);
    throw error;
  }
};

/**
 * Get a shared workout by share code
 */
export const getSharedWorkout = async (shareCode: string) => {
  try {
    // Increment view count
    const { data: share, error: shareError } = await supabase
      .from("workout_shares")
      .select(`
        *,
        workout:workouts(*)
      `)
      .eq("share_code", shareCode)
      .single();

    if (shareError) throw shareError;

    // Increment view count
    await supabase
      .from("workout_shares")
      .update({ view_count: (share.view_count || 0) + 1 })
      .eq("id", share.id);

    return share;
  } catch (error) {
    console.error("Error fetching shared workout:", error);
    throw error;
  }
};

/**
 * Clone a shared workout to user's own workouts
 */
export const cloneSharedWorkout = async (shareCode: string, userId: string) => {
  try {
    // Get the shared workout
    const { data: share, error: shareError } = await supabase
      .from("workout_shares")
      .select(`
        *,
        workout:workouts(*)
      `)
      .eq("share_code", shareCode)
      .single();

    if (shareError) throw shareError;

    const originalWorkout = (share as any).workout;

    if (!originalWorkout) {
      throw new Error("Workout not found");
    }

    // Create a copy of the workout for the user
    const { data: newWorkout, error: workoutError } = await supabase
      .from("workouts")
      .insert({
        user_id: userId,
        name: `${originalWorkout.name} (Copy)`,
        description: originalWorkout.description,
        workout_date: new Date().toISOString(),
        duration_minutes: originalWorkout.duration_minutes,
        notes: originalWorkout.notes,
      })
      .select()
      .single();

    if (workoutError) throw workoutError;

    // Copy workout exercises if they exist
    const { data: exercises } = await supabase
      .from("workout_exercises")
      .select("*")
      .eq("workout_id", originalWorkout.id);

    if (exercises && exercises.length > 0) {
      const exerciseCopies = exercises.map(ex => ({
        workout_id: newWorkout.id,
        exercise_id: ex.exercise_id,
        sets: ex.sets,
        reps: ex.reps,
        weight: ex.weight,
        duration_seconds: ex.duration_seconds,
        distance_meters: ex.distance_meters,
        notes: ex.notes,
        order_index: ex.order_index,
      }));

      await supabase.from("workout_exercises").insert(exerciseCopies);
    }

    return newWorkout;
  } catch (error) {
    console.error("Error cloning shared workout:", error);
    throw error;
  }
};

/**
 * Get all shares for a workout
 */
export const getWorkoutShares = async (workoutId: string): Promise<WorkoutShare[]> => {
  try {
    const { data, error } = await supabase
      .from("workout_shares")
      .select("*")
      .eq("workout_id", workoutId)
      .order("created_at", { ascending: false });

    if (error) throw error;
    return data as WorkoutShare[];
  } catch (error) {
    console.error("Error fetching workout shares:", error);
    throw error;
  }
};

/**
 * Delete a workout share
 */
export const deleteWorkoutShare = async (shareId: string): Promise<void> => {
  try {
    const { error } = await supabase
      .from("workout_shares")
      .delete()
      .eq("id", shareId);

    if (error) throw error;
  } catch (error) {
    console.error("Error deleting workout share:", error);
    throw error;
  }
};

/**
 * Like a workout
 */
export const likeWorkout = async (workoutId: string, userId: string): Promise<WorkoutLike> => {
  try {
    // Check if already liked
    const { data: existing } = await supabase
      .from("workout_likes")
      .select("*")
      .eq("workout_id", workoutId)
      .eq("user_id", userId)
      .single();

    if (existing) {
      return existing as WorkoutLike;
    }

    const { data, error } = await supabase
      .from("workout_likes")
      .insert({
        workout_id: workoutId,
        user_id: userId,
      })
      .select()
      .single();

    if (error) throw error;
    return data as WorkoutLike;
  } catch (error) {
    console.error("Error liking workout:", error);
    throw error;
  }
};

/**
 * Unlike a workout
 */
export const unlikeWorkout = async (workoutId: string, userId: string): Promise<void> => {
  try {
    const { error } = await supabase
      .from("workout_likes")
      .delete()
      .eq("workout_id", workoutId)
      .eq("user_id", userId);

    if (error) throw error;
  } catch (error) {
    console.error("Error unliking workout:", error);
    throw error;
  }
};

/**
 * Get likes for a workout
 */
export const getWorkoutLikes = async (workoutId: string): Promise<WorkoutLike[]> => {
  try {
    const { data, error } = await supabase
      .from("workout_likes")
      .select("*")
      .eq("workout_id", workoutId)
      .order("created_at", { ascending: false });

    if (error) throw error;
    return data as WorkoutLike[];
  } catch (error) {
    console.error("Error fetching workout likes:", error);
    throw error;
  }
};

/**
 * Get like count for a workout
 */
export const getWorkoutLikeCount = async (workoutId: string): Promise<number> => {
  try {
    const { count, error } = await supabase
      .from("workout_likes")
      .select("*", { count: "exact", head: true })
      .eq("workout_id", workoutId);

    if (error) throw error;
    return count || 0;
  } catch (error) {
    console.error("Error fetching workout like count:", error);
    return 0;
  }
};

/**
 * Check if user has liked a workout
 */
export const hasUserLikedWorkout = async (
  workoutId: string,
  userId: string
): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from("workout_likes")
      .select("id")
      .eq("workout_id", workoutId)
      .eq("user_id", userId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        return false;
      }
      throw error;
    }

    return !!data;
  } catch (error) {
    console.error("Error checking like status:", error);
    return false;
  }
};

/**
 * Add a comment to a workout
 */
export const addComment = async (
  workoutId: string,
  userId: string,
  comment: string
): Promise<WorkoutComment> => {
  try {
    const { data, error } = await supabase
      .from("workout_comments")
      .insert({
        workout_id: workoutId,
        user_id: userId,
        comment,
      })
      .select()
      .single();

    if (error) throw error;
    return data as WorkoutComment;
  } catch (error) {
    console.error("Error adding comment:", error);
    throw error;
  }
};

/**
 * Get comments for a workout with user profiles
 */
export const getWorkoutComments = async (workoutId: string): Promise<WorkoutComment[]> => {
  try {
    const { data, error } = await supabase
      .from("workout_comments")
      .select(`
        *,
        user_profile:user_profiles!workout_comments_user_id_fkey(*)
      `)
      .eq("workout_id", workoutId)
      .order("created_at", { ascending: false });

    if (error) throw error;
    return data as any as WorkoutComment[];
  } catch (error) {
    console.error("Error fetching workout comments:", error);
    throw error;
  }
};

/**
 * Delete a comment
 */
export const deleteComment = async (commentId: string): Promise<void> => {
  try {
    const { error } = await supabase
      .from("workout_comments")
      .delete()
      .eq("id", commentId);

    if (error) throw error;
  } catch (error) {
    console.error("Error deleting comment:", error);
    throw error;
  }
};

/**
 * Update a comment
 */
export const updateComment = async (
  commentId: string,
  comment: string
): Promise<WorkoutComment> => {
  try {
    const { data, error } = await supabase
      .from("workout_comments")
      .update({ comment })
      .eq("id", commentId)
      .select()
      .single();

    if (error) throw error;
    return data as WorkoutComment;
  } catch (error) {
    console.error("Error updating comment:", error);
    throw error;
  }
};
